spring.application.name=jupddang

# 1. DB 설정
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Redis 설정
# 로컬 개발에선 localhost, Docker Compose 내부에선 서비스명('redis')을 사용
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}

# 3. JPA 설정
# 운영 배포 시에는 'validate' 또는 'none'을 권장하지만, 초기 배포라 'update' 유지
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# 4. Google Cloud Storage
spring.cloud.gcp.project-id=jupddang
spring.cloud.gcp.credentials.location=file:${GCP_CREDENTIALS_PATH:/app/gcp-credentials.json}
spring.cloud.gcp.storage.bucket=jupddang-images

# 5. 파일 업로드 제한 
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=35MB

# 6. JWT
jwt.secret=jjjjjjjjjjjjjjjuuuuuuuuuupppppppppdddddddddddaaang
jwt.access-exp-min=1440
jwt.issuer=jupddang

# 7. server 신뢰성
server.forward-headers-strategy=framework

spring.profiles.active=local