// Mocks generated by Mockito 5.4.6 from annotations
// in jupddang/test/unit/occupation_distance_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:h3_common/h3_common.dart' as _i3;
import 'package:jupddang/core/network/api_client.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseOptions_1 extends _i1.SmartFake implements _i2.BaseOptions {
  _FakeBaseOptions_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_2 extends _i1.SmartFake implements _i2.Interceptors {
  _FakeInterceptors_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_3 extends _i1.SmartFake
    implements _i2.HttpClientAdapter {
  _FakeHttpClientAdapter_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_4 extends _i1.SmartFake implements _i2.Transformer {
  _FakeTransformer_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_5<T1> extends _i1.SmartFake implements _i2.Response<T1> {
  _FakeResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeoCoord_6 extends _i1.SmartFake implements _i3.GeoCoord {
  _FakeGeoCoord_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCoordIJ_7 extends _i1.SmartFake implements _i3.CoordIJ {
  _FakeCoordIJ_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  set dio(_i2.Dio? value) => super.noSuchMethod(
    Invocation.setter(#dio, value),
    returnValueForMissingStub: null,
  );

  @override
  void setAccessToken(String? token) => super.noSuchMethod(
    Invocation.method(#setAccessToken, [token]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i2.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_1(this, Invocation.getter(#options)),
          )
          as _i2.BaseOptions);

  @override
  _i2.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_2(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i2.Interceptors);

  @override
  _i2.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_3(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i2.HttpClientAdapter);

  @override
  _i2.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_4(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i2.Transformer);

  @override
  set options(_i2.BaseOptions? value) => super.noSuchMethod(
    Invocation.setter(#options, value),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i2.HttpClientAdapter? value) => super.noSuchMethod(
    Invocation.setter(#httpClientAdapter, value),
    returnValueForMissingStub: null,
  );

  @override
  set transformer(_i2.Transformer? value) => super.noSuchMethod(
    Invocation.setter(#transformer, value),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i2.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_5<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    _i2.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_5<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i2.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> fetch<T>(_i2.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i2.Dio clone({
    _i2.BaseOptions? options,
    _i2.Interceptors? interceptors,
    _i2.HttpClientAdapter? httpClientAdapter,
    _i2.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_0(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i2.Dio);
}

/// A class which mocks [H3].
///
/// See the documentation for Mockito's code generation for more information.
class MockH3 extends _i1.Mock implements _i3.H3 {
  MockH3() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool isValidCell(BigInt? h3Index) =>
      (super.noSuchMethod(
            Invocation.method(#isValidCell, [h3Index]),
            returnValue: false,
          )
          as bool);

  @override
  bool isPentagon(BigInt? h3Index) =>
      (super.noSuchMethod(
            Invocation.method(#isPentagon, [h3Index]),
            returnValue: false,
          )
          as bool);

  @override
  bool isResClassIII(BigInt? h3Index) =>
      (super.noSuchMethod(
            Invocation.method(#isResClassIII, [h3Index]),
            returnValue: false,
          )
          as bool);

  @override
  int getBaseCellNumber(BigInt? h3Index) =>
      (super.noSuchMethod(
            Invocation.method(#getBaseCellNumber, [h3Index]),
            returnValue: 0,
          )
          as int);

  @override
  List<int> getIcosahedronFaces(BigInt? h3Index) =>
      (super.noSuchMethod(
            Invocation.method(#getIcosahedronFaces, [h3Index]),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  int getResolution(BigInt? h3Index) =>
      (super.noSuchMethod(
            Invocation.method(#getResolution, [h3Index]),
            returnValue: 0,
          )
          as int);

  @override
  BigInt geoToCell(_i3.GeoCoord? geoCoord, int? resolution) =>
      (super.noSuchMethod(
            Invocation.method(#geoToCell, [geoCoord, resolution]),
            returnValue: _i6.dummyValue<BigInt>(
              this,
              Invocation.method(#geoToCell, [geoCoord, resolution]),
            ),
          )
          as BigInt);

  @override
  _i3.GeoCoord cellToGeo(BigInt? h3Index) =>
      (super.noSuchMethod(
            Invocation.method(#cellToGeo, [h3Index]),
            returnValue: _FakeGeoCoord_6(
              this,
              Invocation.method(#cellToGeo, [h3Index]),
            ),
          )
          as _i3.GeoCoord);

  @override
  List<_i3.GeoCoord> cellToBoundary(BigInt? h3Index) =>
      (super.noSuchMethod(
            Invocation.method(#cellToBoundary, [h3Index]),
            returnValue: <_i3.GeoCoord>[],
          )
          as List<_i3.GeoCoord>);

  @override
  BigInt cellToParent(BigInt? h3Index, int? resolution) =>
      (super.noSuchMethod(
            Invocation.method(#cellToParent, [h3Index, resolution]),
            returnValue: _i6.dummyValue<BigInt>(
              this,
              Invocation.method(#cellToParent, [h3Index, resolution]),
            ),
          )
          as BigInt);

  @override
  List<BigInt> cellToChildren(BigInt? h3Index, int? resolution) =>
      (super.noSuchMethod(
            Invocation.method(#cellToChildren, [h3Index, resolution]),
            returnValue: <BigInt>[],
          )
          as List<BigInt>);

  @override
  int cellToChildrenSize(BigInt? h3Index, int? resolution) =>
      (super.noSuchMethod(
            Invocation.method(#cellToChildrenSize, [h3Index, resolution]),
            returnValue: 0,
          )
          as int);

  @override
  BigInt cellToCenterChild(BigInt? h3Index, int? resolution) =>
      (super.noSuchMethod(
            Invocation.method(#cellToCenterChild, [h3Index, resolution]),
            returnValue: _i6.dummyValue<BigInt>(
              this,
              Invocation.method(#cellToCenterChild, [h3Index, resolution]),
            ),
          )
          as BigInt);

  @override
  int cellToChildPos(BigInt? h3Index, int? parentResolution) =>
      (super.noSuchMethod(
            Invocation.method(#cellToChildPos, [h3Index, parentResolution]),
            returnValue: 0,
          )
          as int);

  @override
  BigInt childPosToCell(
    int? childPosition,
    BigInt? h3Index,
    int? childResolution,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#childPosToCell, [
              childPosition,
              h3Index,
              childResolution,
            ]),
            returnValue: _i6.dummyValue<BigInt>(
              this,
              Invocation.method(#childPosToCell, [
                childPosition,
                h3Index,
                childResolution,
              ]),
            ),
          )
          as BigInt);

  @override
  List<BigInt> gridDisk(BigInt? h3Index, int? ringSize) =>
      (super.noSuchMethod(
            Invocation.method(#gridDisk, [h3Index, ringSize]),
            returnValue: <BigInt>[],
          )
          as List<BigInt>);

  @override
  List<List<BigInt>> gridDiskDistances(BigInt? h3Index, int? ringSize) =>
      (super.noSuchMethod(
            Invocation.method(#gridDiskDistances, [h3Index, ringSize]),
            returnValue: <List<BigInt>>[],
          )
          as List<List<BigInt>>);

  @override
  List<BigInt> gridRingUnsafe(BigInt? h3Index, int? ringSize) =>
      (super.noSuchMethod(
            Invocation.method(#gridRingUnsafe, [h3Index, ringSize]),
            returnValue: <BigInt>[],
          )
          as List<BigInt>);

  @override
  List<BigInt> polygonToCells({
    required List<_i3.GeoCoord>? perimeter,
    required int? resolution,
    List<List<_i3.GeoCoord>>? holes = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#polygonToCells, [], {
              #perimeter: perimeter,
              #resolution: resolution,
              #holes: holes,
            }),
            returnValue: <BigInt>[],
          )
          as List<BigInt>);

  @override
  List<BigInt> polygonToCellsExperimental({
    required List<_i3.GeoCoord>? perimeter,
    required int? resolution,
    List<List<_i3.GeoCoord>>? holes = const [],
    _i3.PolygonToCellFlags? flag = _i3.PolygonToCellFlags.containmentCenter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#polygonToCellsExperimental, [], {
              #perimeter: perimeter,
              #resolution: resolution,
              #holes: holes,
              #flag: flag,
            }),
            returnValue: <BigInt>[],
          )
          as List<BigInt>);

  @override
  List<List<List<_i3.GeoCoord>>> cellsToMultiPolygon(List<BigInt>? h3Indexes) =>
      (super.noSuchMethod(
            Invocation.method(#cellsToMultiPolygon, [h3Indexes]),
            returnValue: <List<List<_i3.GeoCoord>>>[],
          )
          as List<List<List<_i3.GeoCoord>>>);

  @override
  List<BigInt> compactCells(List<BigInt>? h3Set) =>
      (super.noSuchMethod(
            Invocation.method(#compactCells, [h3Set]),
            returnValue: <BigInt>[],
          )
          as List<BigInt>);

  @override
  List<BigInt> uncompactCells(
    List<BigInt>? h3Set, {
    required int? resolution,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uncompactCells,
              [h3Set],
              {#resolution: resolution},
            ),
            returnValue: <BigInt>[],
          )
          as List<BigInt>);

  @override
  bool areNeighborCells(BigInt? origin, BigInt? destination) =>
      (super.noSuchMethod(
            Invocation.method(#areNeighborCells, [origin, destination]),
            returnValue: false,
          )
          as bool);

  @override
  BigInt cellsToDirectedEdge(BigInt? origin, BigInt? destination) =>
      (super.noSuchMethod(
            Invocation.method(#cellsToDirectedEdge, [origin, destination]),
            returnValue: _i6.dummyValue<BigInt>(
              this,
              Invocation.method(#cellsToDirectedEdge, [origin, destination]),
            ),
          )
          as BigInt);

  @override
  BigInt getDirectedEdgeOrigin(BigInt? edgeIndex) =>
      (super.noSuchMethod(
            Invocation.method(#getDirectedEdgeOrigin, [edgeIndex]),
            returnValue: _i6.dummyValue<BigInt>(
              this,
              Invocation.method(#getDirectedEdgeOrigin, [edgeIndex]),
            ),
          )
          as BigInt);

  @override
  BigInt getDirectedEdgeDestination(BigInt? edgeIndex) =>
      (super.noSuchMethod(
            Invocation.method(#getDirectedEdgeDestination, [edgeIndex]),
            returnValue: _i6.dummyValue<BigInt>(
              this,
              Invocation.method(#getDirectedEdgeDestination, [edgeIndex]),
            ),
          )
          as BigInt);

  @override
  bool isValidDirectedEdge(BigInt? edgeIndex) =>
      (super.noSuchMethod(
            Invocation.method(#isValidDirectedEdge, [edgeIndex]),
            returnValue: false,
          )
          as bool);

  @override
  ({BigInt destination, BigInt origin}) directedEdgeToCells(
    BigInt? edgeIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#directedEdgeToCells, [edgeIndex]),
            returnValue: (
              destination: _i6.dummyValue<BigInt>(
                this,
                Invocation.method(#directedEdgeToCells, [edgeIndex]),
              ),
              origin: _i6.dummyValue<BigInt>(
                this,
                Invocation.method(#directedEdgeToCells, [edgeIndex]),
              ),
            ),
          )
          as ({BigInt destination, BigInt origin}));

  @override
  List<BigInt> originToDirectedEdges(BigInt? h3Index) =>
      (super.noSuchMethod(
            Invocation.method(#originToDirectedEdges, [h3Index]),
            returnValue: <BigInt>[],
          )
          as List<BigInt>);

  @override
  List<_i3.GeoCoord> directedEdgeToBoundary(BigInt? edgeIndex) =>
      (super.noSuchMethod(
            Invocation.method(#directedEdgeToBoundary, [edgeIndex]),
            returnValue: <_i3.GeoCoord>[],
          )
          as List<_i3.GeoCoord>);

  @override
  int gridDistance(BigInt? origin, BigInt? destination) =>
      (super.noSuchMethod(
            Invocation.method(#gridDistance, [origin, destination]),
            returnValue: 0,
          )
          as int);

  @override
  List<BigInt> gridPathCells(BigInt? origin, BigInt? destination) =>
      (super.noSuchMethod(
            Invocation.method(#gridPathCells, [origin, destination]),
            returnValue: <BigInt>[],
          )
          as List<BigInt>);

  @override
  _i3.CoordIJ cellToLocalIj(BigInt? origin, BigInt? destination) =>
      (super.noSuchMethod(
            Invocation.method(#cellToLocalIj, [origin, destination]),
            returnValue: _FakeCoordIJ_7(
              this,
              Invocation.method(#cellToLocalIj, [origin, destination]),
            ),
          )
          as _i3.CoordIJ);

  @override
  BigInt localIjToCell(BigInt? origin, _i3.CoordIJ? coordinates) =>
      (super.noSuchMethod(
            Invocation.method(#localIjToCell, [origin, coordinates]),
            returnValue: _i6.dummyValue<BigInt>(
              this,
              Invocation.method(#localIjToCell, [origin, coordinates]),
            ),
          )
          as BigInt);

  @override
  double greatCircleDistance(
    _i3.GeoCoord? a,
    _i3.GeoCoord? b,
    _i3.H3Units? unit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#greatCircleDistance, [a, b, unit]),
            returnValue: 0.0,
          )
          as double);

  @override
  double cellArea(BigInt? h3Index, _i3.H3Units? unit) =>
      (super.noSuchMethod(
            Invocation.method(#cellArea, [h3Index, unit]),
            returnValue: 0.0,
          )
          as double);

  @override
  double edgeLength(BigInt? edge, _i3.H3Units? unit) =>
      (super.noSuchMethod(
            Invocation.method(#edgeLength, [edge, unit]),
            returnValue: 0.0,
          )
          as double);

  @override
  double getHexagonAreaAvg(int? resolution, _i3.H3MetricUnits? unit) =>
      (super.noSuchMethod(
            Invocation.method(#getHexagonAreaAvg, [resolution, unit]),
            returnValue: 0.0,
          )
          as double);

  @override
  double getHexagonEdgeLengthAvg(int? resolution, _i3.H3MetricUnits? unit) =>
      (super.noSuchMethod(
            Invocation.method(#getHexagonEdgeLengthAvg, [resolution, unit]),
            returnValue: 0.0,
          )
          as double);

  @override
  BigInt cellToVertex(BigInt? h3Index, int? vertexNum) =>
      (super.noSuchMethod(
            Invocation.method(#cellToVertex, [h3Index, vertexNum]),
            returnValue: _i6.dummyValue<BigInt>(
              this,
              Invocation.method(#cellToVertex, [h3Index, vertexNum]),
            ),
          )
          as BigInt);

  @override
  List<BigInt> cellToVertexes(BigInt? h3Index) =>
      (super.noSuchMethod(
            Invocation.method(#cellToVertexes, [h3Index]),
            returnValue: <BigInt>[],
          )
          as List<BigInt>);

  @override
  _i3.GeoCoord vertexToGeo(BigInt? h3Index) =>
      (super.noSuchMethod(
            Invocation.method(#vertexToGeo, [h3Index]),
            returnValue: _FakeGeoCoord_6(
              this,
              Invocation.method(#vertexToGeo, [h3Index]),
            ),
          )
          as _i3.GeoCoord);

  @override
  bool isValidVertex(BigInt? h3Index) =>
      (super.noSuchMethod(
            Invocation.method(#isValidVertex, [h3Index]),
            returnValue: false,
          )
          as bool);

  @override
  BigInt getNumCells(int? resolution) =>
      (super.noSuchMethod(
            Invocation.method(#getNumCells, [resolution]),
            returnValue: _i6.dummyValue<BigInt>(
              this,
              Invocation.method(#getNumCells, [resolution]),
            ),
          )
          as BigInt);

  @override
  List<BigInt> getRes0Cells() =>
      (super.noSuchMethod(
            Invocation.method(#getRes0Cells, []),
            returnValue: <BigInt>[],
          )
          as List<BigInt>);

  @override
  List<BigInt> getPentagons(int? resolution) =>
      (super.noSuchMethod(
            Invocation.method(#getPentagons, [resolution]),
            returnValue: <BigInt>[],
          )
          as List<BigInt>);

  @override
  double degsToRads(double? deg) =>
      (super.noSuchMethod(
            Invocation.method(#degsToRads, [deg]),
            returnValue: 0.0,
          )
          as double);

  @override
  double radsToDegs(double? rad) =>
      (super.noSuchMethod(
            Invocation.method(#radsToDegs, [rad]),
            returnValue: 0.0,
          )
          as double);
}
