// Mocks generated by Mockito 5.4.6 from annotations
// in jupddang/test/unit/party_socket_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:typed_data' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:stomp_dart_client/src/stomp.dart' as _i3;
import 'package:stomp_dart_client/src/stomp_config.dart' as _i2;
import 'package:stomp_dart_client/src/stomp_handler.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStompConfig_0 extends _i1.SmartFake implements _i2.StompConfig {
  _FakeStompConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StompClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockStompClient extends _i1.Mock implements _i3.StompClient {
  MockStompClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.StompConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeStompConfig_0(this, Invocation.getter(#config)),
          )
          as _i2.StompConfig);

  @override
  bool get connected =>
      (super.noSuchMethod(Invocation.getter(#connected), returnValue: false)
          as bool);

  @override
  bool get isActive =>
      (super.noSuchMethod(Invocation.getter(#isActive), returnValue: false)
          as bool);

  @override
  void activate() => super.noSuchMethod(
    Invocation.method(#activate, []),
    returnValueForMissingStub: null,
  );

  @override
  void deactivate() => super.noSuchMethod(
    Invocation.method(#deactivate, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.StompUnsubscribe subscribe({
    required String? destination,
    required _i2.StompFrameCallback? callback,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [], {
              #destination: destination,
              #callback: callback,
              #headers: headers,
            }),
            returnValue: ({Map<String, String>? unsubscribeHeaders}) {},
          )
          as _i4.StompUnsubscribe);

  @override
  void send({
    required String? destination,
    Map<String, String>? headers,
    String? body,
    _i5.Uint8List? binaryBody,
  }) => super.noSuchMethod(
    Invocation.method(#send, [], {
      #destination: destination,
      #headers: headers,
      #body: body,
      #binaryBody: binaryBody,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void ack({required String? id, Map<String, String>? headers}) =>
      super.noSuchMethod(
        Invocation.method(#ack, [], {#id: id, #headers: headers}),
        returnValueForMissingStub: null,
      );

  @override
  void nack({required String? id, Map<String, String>? headers}) =>
      super.noSuchMethod(
        Invocation.method(#nack, [], {#id: id, #headers: headers}),
        returnValueForMissingStub: null,
      );
}
